"""
Django settings for DLR project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=p1d@p!%s4kj=p&7og149wvuxkz+0u!61_0ax&3$e0!21=9f#8"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "lcc",
    "ragflow",
    "qanything",
]

# 自定义用户模型
AUTH_USER_MODEL = 'lcc.User'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "DLR.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'DLR' / 'templates', BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "DLR.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "ai_chat_db",
        "USER": "root",
        "PASSWORD": "123456",  # 请修改为您的MySQL密码
        "HOST": "localhost",
        "PORT": "3307",  # 使用phpStudy MySQL 8.0.12的端口
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}

# Redis配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 会话配置
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 86400  # 24小时
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # 开发环境设为False，生产环境设为True


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
LCC_API_BASE_URL = "http://127.0.0.1:7861/chat"
LCC_DEFAULT_MODEL = "deepseek-r1"

# Chatchat知识库配置
CHATCHAT_API_BASE_URL = "http://127.0.0.1:7861"
CHATCHAT_DEFAULT_EMBED_MODEL = "bge-large-zh-v1.5"
CHATCHAT_DEFAULT_VECTOR_STORE = "faiss"

# 知识库内容显示配置
KNOWLEDGE_BASE_CONFIG = {
    'DEFAULT_MAX_CONTENT_LENGTH': 0,     # 默认最大内容长度（0表示不限制）
    'SEARCH_MAX_CONTENT_LENGTH': 0,      # 搜索结果最大内容长度（0表示不限制）
    'CHAT_MAX_CONTENT_LENGTH': 0,        # 对话中最大内容长度（0表示不限制）
    'DEFAULT_TOP_K': 3,                  # 默认返回文档数量
    'DEFAULT_SCORE_THRESHOLD': 0.5,      # 默认相似度阈值
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Neo4j数据库配置
NEO4J_CONFIG = {
    'URI': 'bolt://localhost:7687',
    'USER': 'neo4j',
    'PASSWORD': 'kg123456',
    'DATABASE': 'neo4j',
}

# 知识图谱配置
KNOWLEDGE_GRAPH_CONFIG = {
    'DEFAULT_DOMAIN': 'general',
    'MAX_ENTITIES_PER_DOCUMENT': 1000,
    'MAX_RELATIONS_PER_DOCUMENT': 500,
    'ENTITY_CONFIDENCE_THRESHOLD': 0.7,
    'RELATION_CONFIDENCE_THRESHOLD': 0.6,
}

# 文件上传配置（用于知识图谱文档）
import os
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# 允许的文档格式
ALLOWED_DOCUMENT_EXTENSIONS = ['.pdf', '.txt', '.docx', '.doc']
MAX_DOCUMENT_SIZE = 50 * 1024 * 1024  # 50MB
