# Generated by Django 4.2.7 on 2025-07-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lcc", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="conversation",
            table="lcc_conversations",
        ),
        migrations.AlterModelTable(
            name="message",
            table="lcc_messages",
        ),
        migrations.AlterModelTable(
            name="user",
            table="lcc_users",
        ),
        migrations.AlterModelTable(
            name="usersession",
            table="lcc_user_sessions",
        ),
    ]
