# Generated by Django 5.2.4 on 2025-08-10 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcc", "0002_fix_table_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="类型名称"
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="显示标签")),
                ("description", models.TextField(blank=True, verbose_name="类型描述")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basic", "基础类型"),
                            ("domain", "领域类型"),
                            ("custom", "自定义类型"),
                        ],
                        default="basic",
                        max_length=20,
                        verbose_name="类型分类",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#cccccc", max_length=7, verbose_name="显示颜色"
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "extraction_patterns",
                    models.JSONField(default=list, verbose_name="提取模式"),
                ),
                (
                    "validation_rules",
                    models.JSONField(default=dict, verbose_name="验证规则"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "实体类型",
                "verbose_name_plural": "实体类型",
                "db_table": "lcc_entity_types",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="文档标题")),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_path",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="文件路径"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF文档"),
                            ("docx", "Word文档"),
                            ("doc", "Word文档(旧版)"),
                            ("txt", "文本文档"),
                            ("html", "HTML文档"),
                            ("md", "Markdown文档"),
                            ("xlsx", "Excel文档"),
                            ("pptx", "PowerPoint文档"),
                        ],
                        max_length=10,
                        verbose_name="文件类型",
                    ),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                (
                    "file_hash",
                    models.CharField(max_length=64, verbose_name="文件哈希值"),
                ),
                ("content", models.TextField(blank=True, verbose_name="文档内容")),
                ("summary", models.TextField(blank=True, verbose_name="文档摘要")),
                (
                    "language",
                    models.CharField(default="zh", max_length=10, verbose_name="语言"),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=100, verbose_name="作者"),
                ),
                (
                    "publish_date",
                    models.DateField(blank=True, null=True, verbose_name="发布日期"),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "处理失败"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(default=0, verbose_name="处理耗时(秒)"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "entity_extracted",
                    models.IntegerField(default=0, verbose_name="提取实体数"),
                ),
                (
                    "relation_extracted",
                    models.IntegerField(default=0, verbose_name="提取关系数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="扩展元数据")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档来源",
                "verbose_name_plural": "文档来源",
                "db_table": "lcc_document_sources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="图谱名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="图谱描述")),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("general", "通用领域"),
                            ("technology", "科技领域"),
                            ("medical", "医学领域"),
                            ("legal", "法律领域"),
                            ("finance", "金融领域"),
                            ("education", "教育领域"),
                            ("business", "商业领域"),
                            ("science", "科学领域"),
                            ("culture", "文化领域"),
                            ("sports", "体育领域"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="应用领域",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "创建中"),
                            ("active", "活跃"),
                            ("inactive", "非活跃"),
                            ("error", "错误"),
                            ("archived", "已归档"),
                        ],
                        default="creating",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "entity_count",
                    models.IntegerField(default=0, verbose_name="实体数量"),
                ),
                (
                    "relation_count",
                    models.IntegerField(default=0, verbose_name="关系数量"),
                ),
                (
                    "document_count",
                    models.IntegerField(default=0, verbose_name="文档数量"),
                ),
                (
                    "neo4j_database",
                    models.CharField(
                        default="neo4j", max_length=50, verbose_name="Neo4j数据库名"
                    ),
                ),
                (
                    "entity_confidence_threshold",
                    models.FloatField(default=0.7, verbose_name="实体置信度阈值"),
                ),
                (
                    "relation_confidence_threshold",
                    models.FloatField(default=0.6, verbose_name="关系置信度阈值"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后处理时间"
                    ),
                ),
                ("config", models.JSONField(default=dict, verbose_name="扩展配置")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识图谱",
                "verbose_name_plural": "知识图谱",
                "db_table": "lcc_knowledge_graphs",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="EntityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "neo4j_id",
                    models.CharField(max_length=100, verbose_name="Neo4j节点ID"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="实体名称")),
                ("description", models.TextField(blank=True, verbose_name="实体描述")),
                ("confidence", models.FloatField(verbose_name="置信度")),
                ("source_text", models.TextField(blank=True, verbose_name="来源文本")),
                (
                    "extraction_method",
                    models.CharField(max_length=50, verbose_name="提取方法"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否已验证"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("properties", models.JSONField(default=dict, verbose_name="扩展属性")),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lcc.documentsource",
                        verbose_name="来源文档",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="验证者",
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lcc.entitytype",
                        verbose_name="实体类型",
                    ),
                ),
                (
                    "knowledge_graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lcc.knowledgegraph",
                        verbose_name="所属图谱",
                    ),
                ),
            ],
            options={
                "verbose_name": "实体记录",
                "verbose_name_plural": "实体记录",
                "db_table": "lcc_entity_records",
                "ordering": ["-created_at"],
                "unique_together": {("knowledge_graph", "neo4j_id")},
            },
        ),
        migrations.AddField(
            model_name="documentsource",
            name="knowledge_graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lcc.knowledgegraph",
                verbose_name="所属图谱",
            ),
        ),
        migrations.CreateModel(
            name="ProcessingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("document_upload", "文档上传"),
                            ("entity_extraction", "实体提取"),
                            ("relation_extraction", "关系提取"),
                            ("graph_construction", "图谱构建"),
                            ("graph_update", "图谱更新"),
                            ("graph_merge", "图谱合并"),
                            ("data_import", "数据导入"),
                            ("data_export", "数据导出"),
                        ],
                        max_length=30,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=200, verbose_name="任务名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度百分比")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "execution_time",
                    models.FloatField(default=0, verbose_name="执行时间(秒)"),
                ),
                (
                    "result_summary",
                    models.TextField(blank=True, verbose_name="结果摘要"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "entities_processed",
                    models.IntegerField(default=0, verbose_name="处理实体数"),
                ),
                (
                    "relations_processed",
                    models.IntegerField(default=0, verbose_name="处理关系数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("config", models.JSONField(default=dict, verbose_name="任务配置")),
                (
                    "result_data",
                    models.JSONField(default=dict, verbose_name="结果数据"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "knowledge_graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lcc.knowledgegraph",
                        verbose_name="所属图谱",
                    ),
                ),
            ],
            options={
                "verbose_name": "处理任务",
                "verbose_name_plural": "处理任务",
                "db_table": "lcc_processing_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("entity_search", "实体搜索"),
                            ("relation_query", "关系查询"),
                            ("path_finding", "路径查找"),
                            ("graph_analysis", "图分析"),
                            ("qa_query", "问答查询"),
                            ("cypher_query", "Cypher查询"),
                        ],
                        max_length=20,
                        verbose_name="查询类型",
                    ),
                ),
                ("query_text", models.TextField(verbose_name="查询文本")),
                (
                    "cypher_query",
                    models.TextField(blank=True, verbose_name="Cypher查询"),
                ),
                (
                    "result_count",
                    models.IntegerField(default=0, verbose_name="结果数量"),
                ),
                (
                    "execution_time",
                    models.FloatField(default=0, verbose_name="执行时间(毫秒)"),
                ),
                (
                    "is_successful",
                    models.BooleanField(default=True, verbose_name="是否成功"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="查询时间"),
                ),
                (
                    "query_params",
                    models.JSONField(default=dict, verbose_name="查询参数"),
                ),
                (
                    "result_data",
                    models.JSONField(default=dict, verbose_name="结果数据"),
                ),
                (
                    "knowledge_graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lcc.knowledgegraph",
                        verbose_name="所属图谱",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="查询用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "查询历史",
                "verbose_name_plural": "查询历史",
                "db_table": "lcc_query_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RelationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="关系名称"
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="显示标签")),
                ("description", models.TextField(blank=True, verbose_name="关系描述")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basic", "基础关系"),
                            ("semantic", "语义关系"),
                            ("temporal", "时间关系"),
                            ("spatial", "空间关系"),
                            ("social", "社会关系"),
                            ("domain", "领域关系"),
                            ("custom", "自定义关系"),
                        ],
                        default="basic",
                        max_length=20,
                        verbose_name="关系分类",
                    ),
                ),
                (
                    "is_symmetric",
                    models.BooleanField(default=False, verbose_name="是否对称关系"),
                ),
                (
                    "is_transitive",
                    models.BooleanField(default=False, verbose_name="是否传递关系"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "extraction_patterns",
                    models.JSONField(default=list, verbose_name="提取模式"),
                ),
                (
                    "validation_rules",
                    models.JSONField(default=dict, verbose_name="验证规则"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="source_relations",
                        to="lcc.entitytype",
                        verbose_name="源实体类型",
                    ),
                ),
                (
                    "target_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="target_relations",
                        to="lcc.entitytype",
                        verbose_name="目标实体类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "关系类型",
                "verbose_name_plural": "关系类型",
                "db_table": "lcc_relation_types",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="RelationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "neo4j_id",
                    models.CharField(max_length=100, verbose_name="Neo4j关系ID"),
                ),
                ("confidence", models.FloatField(verbose_name="置信度")),
                ("source_text", models.TextField(blank=True, verbose_name="来源文本")),
                (
                    "extraction_method",
                    models.CharField(max_length=50, verbose_name="提取方法"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否已验证"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("properties", models.JSONField(default=dict, verbose_name="扩展属性")),
                (
                    "knowledge_graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lcc.knowledgegraph",
                        verbose_name="所属图谱",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lcc.documentsource",
                        verbose_name="来源文档",
                    ),
                ),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_relations",
                        to="lcc.entityrecord",
                        verbose_name="源实体",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_relations",
                        to="lcc.entityrecord",
                        verbose_name="目标实体",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="验证者",
                    ),
                ),
                (
                    "relation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lcc.relationtype",
                        verbose_name="关系类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "关系记录",
                "verbose_name_plural": "关系记录",
                "db_table": "lcc_relation_records",
                "ordering": ["-created_at"],
                "unique_together": {("knowledge_graph", "neo4j_id")},
            },
        ),
    ]
